/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranscriptionTestRouteImport } from './routes/transcription-test'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RestrictedRouteImport } from './routes/restricted'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardFavouritesRouteImport } from './routes/dashboard.favourites'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard.earnings'
import { Route as DashboardBidsRouteImport } from './routes/dashboard.bids'
import { Route as DashboardActiveRouteImport } from './routes/dashboard.active'

const TranscriptionTestRoute = TranscriptionTestRouteImport.update({
  id: '/transcription-test',
  path: '/transcription-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RestrictedRoute = RestrictedRouteImport.update({
  id: '/restricted',
  path: '/restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavouritesRoute = DashboardFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBidsRoute = DashboardBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActiveRoute = DashboardActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/restricted': typeof RestrictedRoute
  '/signup': typeof SignupRoute
  '/transcription-test': typeof TranscriptionTestRoute
  '/dashboard/active': typeof DashboardActiveRoute
  '/dashboard/bids': typeof DashboardBidsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/favourites': typeof DashboardFavouritesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/restricted': typeof RestrictedRoute
  '/signup': typeof SignupRoute
  '/transcription-test': typeof TranscriptionTestRoute
  '/dashboard/active': typeof DashboardActiveRoute
  '/dashboard/bids': typeof DashboardBidsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/favourites': typeof DashboardFavouritesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/restricted': typeof RestrictedRoute
  '/signup': typeof SignupRoute
  '/transcription-test': typeof TranscriptionTestRoute
  '/dashboard/active': typeof DashboardActiveRoute
  '/dashboard/bids': typeof DashboardBidsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/favourites': typeof DashboardFavouritesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/categories'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/restricted'
    | '/signup'
    | '/transcription-test'
    | '/dashboard/active'
    | '/dashboard/bids'
    | '/dashboard/earnings'
    | '/dashboard/favourites'
    | '/dashboard/notifications'
    | '/dashboard/portfolio'
    | '/jobs/$jobId'
    | '/dashboard/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/restricted'
    | '/signup'
    | '/transcription-test'
    | '/dashboard/active'
    | '/dashboard/bids'
    | '/dashboard/earnings'
    | '/dashboard/favourites'
    | '/dashboard/notifications'
    | '/dashboard/portfolio'
    | '/jobs/$jobId'
    | '/dashboard'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/categories'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/restricted'
    | '/signup'
    | '/transcription-test'
    | '/dashboard/active'
    | '/dashboard/bids'
    | '/dashboard/earnings'
    | '/dashboard/favourites'
    | '/dashboard/notifications'
    | '/dashboard/portfolio'
    | '/jobs/$jobId'
    | '/dashboard/'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RestrictedRoute: typeof RestrictedRoute
  SignupRoute: typeof SignupRoute
  TranscriptionTestRoute: typeof TranscriptionTestRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transcription-test': {
      id: '/transcription-test'
      path: '/transcription-test'
      fullPath: '/transcription-test'
      preLoaderRoute: typeof TranscriptionTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restricted': {
      id: '/restricted'
      path: '/restricted'
      fullPath: '/restricted'
      preLoaderRoute: typeof RestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favourites': {
      id: '/dashboard/favourites'
      path: '/favourites'
      fullPath: '/dashboard/favourites'
      preLoaderRoute: typeof DashboardFavouritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bids': {
      id: '/dashboard/bids'
      path: '/bids'
      fullPath: '/dashboard/bids'
      preLoaderRoute: typeof DashboardBidsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/active': {
      id: '/dashboard/active'
      path: '/active'
      fullPath: '/dashboard/active'
      preLoaderRoute: typeof DashboardActiveRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActiveRoute: typeof DashboardActiveRoute
  DashboardBidsRoute: typeof DashboardBidsRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardFavouritesRoute: typeof DashboardFavouritesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActiveRoute: DashboardActiveRoute,
  DashboardBidsRoute: DashboardBidsRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardFavouritesRoute: DashboardFavouritesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RestrictedRoute: RestrictedRoute,
  SignupRoute: SignupRoute,
  TranscriptionTestRoute: TranscriptionTestRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
